[workspace]
resolver = "2"
members = ["day*"]

[workspace.dependencies]
thiserror = "1.0.50"
nom = "7.1.3"
rayon = "1.8.0"
num = "0.4.1"
strum = "0.25"
strum_macros = "0.25"
itertools = "0.12"
cached = "0.46"
array2d = "0.3.1"
pathfinding = "4.6.0"
polygonical = "0.5.0"

