[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"

[dependencies]
array2d = { workspace = true }
nom = { workspace = true }
polygonical = { workspace = true }

