[package]
name = "day24"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"

[dependencies]
nom = { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }

